%YAML 1.1
---
version: '@head'
export: |

    project "Fmt"
        kind "StaticLib"
        files "inclue/fmt/**.cc"

        zpm.export [[
            includedirs "include"
            cppdialect "C++11"
        ]]
...
%YAML 1.1
---
version: '>0.0.0'
export: |

    project "Fmt"

        kind "StaticLib"
        files "fmt/**.cc" 

        zpm.export [[
            includedirs "./"
            cppdialect "C++11"
        ]]
...
