%YAML 1.1
---
version: '@head'
export: |

    project "Fmt"
        kind "StaticLib"
        files "include/fmt/**.cc"

        zpm.export [[
            includedirs "include"
            cppdialect "C++14"
        ]]
...
---
version: '^5.0.0'
export: |

    project "Fmt"

        kind "StaticLib"
        files "src/**.cc" 

        zpm.export [[
            includedirs "include"
            cppdialect "C++14"
        ]]
...

---
version: '>0.0.0'
export: |

    project "Fmt"

        kind "StaticLib"
        files "fmt/**.cc" 

        zpm.export [[
            includedirs "./"
            cppdialect "C++11"
        ]]
...
