sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: linux
    dist: trusty
    env: VERSION=5
  - os: osx
    osx_image: xcode8
    language: generic
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition Fmt
notifications:
  slack:
    secure: WX6D9LPK4UTwze7jTrt2McMViu9/hRBL3OxtyxRA9WalDYeHdFWjJBKICrfe926I8DAUiJHW4w+LhnLo5uIi+oDuwjzGuuZoRjg+leg8CL0QjiWKB2iSFdnNe2Wsr9Rxbh5evcWilAsclV1uh7ATFNc0wAK2vS57wJsE88Qk8zQ8fPEEBhBJioV+WDm/8nA6Ek3yWk6U0EdQXEwbQEFiEhYEWn9R7FuGruKvVT2lBpllBM9akRHq/lrrYVu7ojIGhRzl4RHowuRd2jOUtm+dTjJHt/dg2DrsQdKamL8vnSfIIMWhnBBB6Dd1WX+hK7kFRZzc/pDZ9jUGuJCvHYLB+eHhgaPG389hL2odzKL+OI6K+a30KQHOz29JAvXiUpWfTwKyDiT8Xn4UIIpolqcVBqQq4Uw22myq29zBqeDIkgkH4yNcn67qs6o3A++TbWdCCH4lKZRpEv0tixMLYSj8YgfdY3yOvSqDpTUiK2B6fLpyHXOyMHFBALQ30Qc1apmac0VBW0q6zZUlrukYP5GDiPw6Q1SYyvT/3BavzaCbtvv/NaFpnyjKRKkT/iznZ+6TS9R+z6vowxVK/bDiYf6/beHJQSDpw5gPJWIESO3GR27S8lCb5LDhCRPexZpUFQulrZg+X18K6Aj/hO9jMAplfo48heV7odf+KY5yLvjUvbk=
